### ISSUE TITLE
Warning message about interference if WIFI is enabled

### ISSUE THREAD

**Issue by zorazor** [AppGround-io/bluetooth-gamepad-support#3]
Hello,

many users may not know that Bluetooth and WIFI can interfere with each other.

It would be too bad if the gamepad-app would receive unfairly negative ratings... e.g. for input delay and connection aborts.

To prevent this you could check if WIFI is enabled and if it is, show a warning message.

**Comment by eErenYeager** [comment]
yes, i also noticed it. while Hotspot is active Bluetooth connecting is no stable it get disconnected or delayed

**Comment by AppGround-io** [comment]
Thank you for the suggestion. I added a warning to the Keyboard & Mouse app when a WiFi with 2.4GHz or a hotspot is used. The gamepad app will have this warning in the next version as well.
