### ISSUE TITLE
button spacing issue 

### ISSUE THREAD

**Issue by eErenYeager** [AppGround-io/bluetooth-gamepad-support#6]
![Screenshot_20201008-111027_Bluetooth_Gamepad](https://user-images.githubusercontent.com/42389676/95419655-b0538380-0957-11eb-9cbb-975d2faa56b5.png)
plz fix this. 
I have to slide on D-pad to navigate. but it would be easier if i can navigate by simply clicking.

**Comment by AppGround-io** [comment]
Should be fixed with the latest version
